package resource_proxy_demo.model;

public class RmMetaResourceGroupTypeT {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rm_meta_resource_group_type_t.id
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rm_meta_resource_group_type_t.name
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rm_meta_resource_group_type_t.description
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rm_meta_resource_group_type_t.editable
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    private Byte editable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rm_meta_resource_group_type_t.id
     *
     * @return the value of rm_meta_resource_group_type_t.id
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rm_meta_resource_group_type_t.id
     *
     * @param id the value for rm_meta_resource_group_type_t.id
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rm_meta_resource_group_type_t.name
     *
     * @return the value of rm_meta_resource_group_type_t.name
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rm_meta_resource_group_type_t.name
     *
     * @param name the value for rm_meta_resource_group_type_t.name
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rm_meta_resource_group_type_t.description
     *
     * @return the value of rm_meta_resource_group_type_t.description
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rm_meta_resource_group_type_t.description
     *
     * @param description the value for rm_meta_resource_group_type_t.description
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rm_meta_resource_group_type_t.editable
     *
     * @return the value of rm_meta_resource_group_type_t.editable
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    public Byte getEditable() {
        return editable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rm_meta_resource_group_type_t.editable
     *
     * @param editable the value for rm_meta_resource_group_type_t.editable
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    public void setEditable(Byte editable) {
        this.editable = editable;
    }
}