package resource_proxy_demo.model;

public class RmResourceInstanceT {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rm_resource_instance_t.id
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rm_resource_instance_t.name
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rm_resource_instance_t.id
     *
     * @return the value of rm_resource_instance_t.id
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rm_resource_instance_t.id
     *
     * @param id the value for rm_resource_instance_t.id
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rm_resource_instance_t.name
     *
     * @return the value of rm_resource_instance_t.name
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rm_resource_instance_t.name
     *
     * @param name the value for rm_resource_instance_t.name
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }
}