package resource_proxy_demo.model;

public class RmResourceMonitorT {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rm_resource_monitor_t.id
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rm_resource_monitor_t.ri_id
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    private Integer riId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rm_resource_monitor_t.status
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rm_resource_monitor_t.id
     *
     * @return the value of rm_resource_monitor_t.id
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rm_resource_monitor_t.id
     *
     * @param id the value for rm_resource_monitor_t.id
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rm_resource_monitor_t.ri_id
     *
     * @return the value of rm_resource_monitor_t.ri_id
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    public Integer getRiId() {
        return riId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rm_resource_monitor_t.ri_id
     *
     * @param riId the value for rm_resource_monitor_t.ri_id
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    public void setRiId(Integer riId) {
        this.riId = riId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rm_resource_monitor_t.status
     *
     * @return the value of rm_resource_monitor_t.status
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rm_resource_monitor_t.status
     *
     * @param status the value for rm_resource_monitor_t.status
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}