package resource_proxy_demo.model;

public class RmResourceNodeT {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rm_resource_node_t.id
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rm_resource_node_t.ri_id
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    private Integer riId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rm_resource_node_t.name
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rm_resource_node_t.parent_id
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rm_resource_node_t.group_id
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rm_resource_node_t.is_root
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    private Byte isRoot;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rm_resource_node_t.id
     *
     * @return the value of rm_resource_node_t.id
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rm_resource_node_t.id
     *
     * @param id the value for rm_resource_node_t.id
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rm_resource_node_t.ri_id
     *
     * @return the value of rm_resource_node_t.ri_id
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    public Integer getRiId() {
        return riId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rm_resource_node_t.ri_id
     *
     * @param riId the value for rm_resource_node_t.ri_id
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    public void setRiId(Integer riId) {
        this.riId = riId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rm_resource_node_t.name
     *
     * @return the value of rm_resource_node_t.name
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rm_resource_node_t.name
     *
     * @param name the value for rm_resource_node_t.name
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rm_resource_node_t.parent_id
     *
     * @return the value of rm_resource_node_t.parent_id
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rm_resource_node_t.parent_id
     *
     * @param parentId the value for rm_resource_node_t.parent_id
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rm_resource_node_t.group_id
     *
     * @return the value of rm_resource_node_t.group_id
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rm_resource_node_t.group_id
     *
     * @param groupId the value for rm_resource_node_t.group_id
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rm_resource_node_t.is_root
     *
     * @return the value of rm_resource_node_t.is_root
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    public Byte getIsRoot() {
        return isRoot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rm_resource_node_t.is_root
     *
     * @param isRoot the value for rm_resource_node_t.is_root
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    public void setIsRoot(Byte isRoot) {
        this.isRoot = isRoot;
    }
}