package resource_proxy_demo.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import resource_proxy_demo.model.RmMetaResourceGroupTypeT;
import resource_proxy_demo.model.RmMetaResourceGroupTypeTExample;

public interface RmMetaResourceGroupTypeTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rm_meta_resource_group_type_t
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    long countByExample(RmMetaResourceGroupTypeTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rm_meta_resource_group_type_t
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    int deleteByExample(RmMetaResourceGroupTypeTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rm_meta_resource_group_type_t
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    int insert(RmMetaResourceGroupTypeT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rm_meta_resource_group_type_t
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    int insertSelective(RmMetaResourceGroupTypeT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rm_meta_resource_group_type_t
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    List<RmMetaResourceGroupTypeT> selectByExample(RmMetaResourceGroupTypeTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rm_meta_resource_group_type_t
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    int updateByExampleSelective(@Param("record") RmMetaResourceGroupTypeT record, @Param("example") RmMetaResourceGroupTypeTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rm_meta_resource_group_type_t
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    int updateByExample(@Param("record") RmMetaResourceGroupTypeT record, @Param("example") RmMetaResourceGroupTypeTExample example);
}