package resource_proxy_demo.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import resource_proxy_demo.model.RmResourceGroupT;
import resource_proxy_demo.model.RmResourceGroupTExample;

public interface RmResourceGroupTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rm_resource_group_t
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    long countByExample(RmResourceGroupTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rm_resource_group_t
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    int deleteByExample(RmResourceGroupTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rm_resource_group_t
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    int insert(RmResourceGroupT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rm_resource_group_t
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    int insertSelective(RmResourceGroupT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rm_resource_group_t
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    List<RmResourceGroupT> selectByExample(RmResourceGroupTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rm_resource_group_t
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    int updateByExampleSelective(@Param("record") RmResourceGroupT record, @Param("example") RmResourceGroupTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rm_resource_group_t
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    int updateByExample(@Param("record") RmResourceGroupT record, @Param("example") RmResourceGroupTExample example);
}