package resource_proxy_demo.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import resource_proxy_demo.model.RmResourceInstanceT;
import resource_proxy_demo.model.RmResourceInstanceTExample;

public interface RmResourceInstanceTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rm_resource_instance_t
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    long countByExample(RmResourceInstanceTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rm_resource_instance_t
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    int deleteByExample(RmResourceInstanceTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rm_resource_instance_t
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    int insert(RmResourceInstanceT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rm_resource_instance_t
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    int insertSelective(RmResourceInstanceT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rm_resource_instance_t
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    List<RmResourceInstanceT> selectByExample(RmResourceInstanceTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rm_resource_instance_t
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    int updateByExampleSelective(@Param("record") RmResourceInstanceT record, @Param("example") RmResourceInstanceTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rm_resource_instance_t
     *
     * @mbg.generated Fri Nov 23 11:43:34 CST 2018
     */
    int updateByExample(@Param("record") RmResourceInstanceT record, @Param("example") RmResourceInstanceTExample example);
}